sudo: required
language: python
services:
  - docker
python:
  - "3.6"
before_script:
  - docker-compose build
script:
  - docker-compose run --rm web bash -c "flake8 . &&
                                         python wait_for_postgres.py &&
                                         ./manage.py test"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login --username=_ --password="$HEROKU_AUTH_TOKEN" registry.heroku.com;
    docker tag web registry.heroku.com/{{cookiecutter.app_name}}-prod/web;
    docker push registry.heroku.com/{{cookiecutter.app_name}}-prod/web;
    fi
  - if [ "$TRAVIS_BRANCH" == "qa" ]; then
    docker login --username=_ --password="$HEROKU_AUTH_TOKEN" registry.heroku.com;
    docker tag web registry.heroku.com/{{cookiecutter.app_name}}-qa/web;
    docker push registry.heroku.com/{{cookiecutter.app_name}}-qa/web;
    fi

notifications:
  email: false

cache:
  pip: true
