language: python
services:
  - postgresql
  - redis-server
python:
  - "2.7"
before_script:
- export DATABASE_URL=postgres://postgres@localhost/{{ cookiecutter.app_name }}
- export DJANGO_SECRET=`openssl rand -base64 32`
- psql -c 'CREATE DATABASE "{{ cookiecutter.app_name }}";' -U postgres
install:
  - "pip install -r requirements/test.txt"
script:
  - ./{{cookiecutter.app_name}}/manage.py test {{cookiecutter.app_name}}
after_success:
  - coveralls

deploy:
  provider: heroku
  app:
    master: {{cookiecutter.app_name}}-dev
    qa: {{cookiecutter.app_name}}-qa
    prod: {{cookiecutter.app_name}}-prod
  on:
    repo: {{cookiecutter.github_username}}/{{cookiecutter.github_repository_name}}
  run:
    - "./{{cookiecutter.app_name}}/manage.py migrate"

notifications:
  email: false

# This reportedly works around an issue downloading packages from pypi on
# travis. Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false

matrix:
  fast_finish: true

cache: pip
