site_name: {{cookiecutter.app_name}}
site_description: {{cookiecutter.description}}
repo_url: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.github_repository_name}}
site_dir: site
copyright: Copyright &copy; 2015, <a href="https://github.com/{{cookiecutter.github_username}}">{{cookiecutter.github_username}}</a>.

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'