sudo: required
language: python
python:
  - "3.6"
services:
  - docker
install:
  - pip install cookiecutter
  - cookiecutter . --no-input
  - cd piedpiper-web
script:
  - docker-compose run --rm web bash -c "flake8 . &&
                                         python wait_for_postgres.py &&
                                         ./piedpiper/manage.py test"
notifications:
  email: false
cache:
  pip: True
